# Generated by Django 4.0 on 2023-07-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='patdoc',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patreg',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
