# Generated by Django 4.0 on 2023-07-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patdoc_userid_patreg_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='patien_dise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('disease', models.CharField(max_length=100)),
                ('specilaist', models.CharField(max_length=100)),
            ],
        ),
    ]
