# Generated by Django 4.0 on 2023-07-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patien_dise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifydatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padid', models.IntegerField()),
                ('docid', models.IntegerField()),
                ('pred', models.CharField(max_length=50)),
            ],
        ),
    ]
