# Generated by Django 4.0 on 2023-07-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notifydatabase_patname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padid', models.IntegerField()),
                ('patname', models.CharField(max_length=50)),
                ('pred', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('docid', models.IntegerField()),
                ('doc_name', models.CharField(max_length=50)),
            ],
        ),
    ]
