# Generated by Django 4.0 on 2023-07-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_appoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='city1',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appoint',
            name='hospital_name',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appoint',
            name='phno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
