# Generated by Django 4.0 on 2023-07-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_appoint_city1_appoint_hospital_name_appoint_phno'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='hospin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appoint',
            name='patphno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
