# Generated by Django 4.0 on 2023-07-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_appoint_hospin_appoint_patphno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='patphno',
            field=models.BigIntegerField(),
        ),
    ]
