# Generated by Django 4.0 on 2023-07-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_appoint_patphno'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
