# Generated by Django 4.0 on 2023-07-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_appoint_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patid', models.IntegerField()),
                ('docid', models.IntegerField()),
                ('treat', models.CharField(max_length=20)),
            ],
        ),
    ]
