# Generated by Django 4.0 on 2023-07-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_appoint_phno'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='unique_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
